[Errno 2] No such file or directory: '/home/LAB/changc/etbert/datasets/cross_platform/etbert/testdataset/'
Dataset directory /home/LAB/changc/etbert/datasets/cross_platform/etbert/testdataset/ not exist.
Begin to obtain new dataset.
label_name_list ['b612kaji.pcap']
session_pcap_path {}

Begin to generate features.
0it [00:00, ?it/s]0it [00:00, ?it/s]
label_id dict_items([('b612kaji.pcap', 0)])
dataset dict_items([])
Traceback (most recent call last):
  File "/home/LAB/changc/etbert/data_process/main.py", line 342, in <module>
    main()
  File "/home/LAB/changc/.conda/envs/ET-BERT/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/LAB/changc/.conda/envs/ET-BERT/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/LAB/changc/.conda/envs/ET-BERT/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/LAB/changc/.conda/envs/ET-BERT/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/LAB/changc/etbert/data_process/main.py", line 339, in main
    dataset_extract(train_model)
  File "/home/LAB/changc/etbert/data_process/main.py", line 87, in dataset_extract
    X, Y = dataset_generation.generation(
  File "/home/LAB/changc/etbert/data_process/dataset_generation.py", line 601, in generation
    dataset[label_id[label_name_list[index]]]["samples"],
KeyError: 0
